Fix rendering sprites in a different way.
jlowry/amethyst pull request #2
Opened 2020-07-06 03:59 UTC by CleanCut

This approach goes directly to creating an orthographic camera with the desired projection.  Perhaps it better illustrates either the bug within Projection::orthographic() or my misunderstanding of how it is supposed to work.

I set the screen to black as well. The rest of the changes are just `rustfmt`.

Compare to https://github.com/jlowry/amethyst/pull/1

2020-07-06 10:15 UTC, valkum commented
Hmm. Long time since i spent my nights on that. IIRC both projective and orthographic cameras behave the same as in they point into the same direction which means without any translation point with z<0 would be further away. We wrote tests to ensure everything is correct.

2020-07-06 16:15 UTC, CleanCut commented
@valkum Would you have expected [this projection](https://github.com/jlowry/amethyst/pull/2/files#diff-09f645b3215c88ce31919f76f55dac90R102-R111) to have worked ()?  That's what really confuses me...why doesn't that work?

2020-07-06 16:29 UTC, valkum commented
Maybe having the camera and the paddle at z=0 causes the culling to jump in because of floating point errors? 
The projection should map everything in-between the far plane and the near plane into 0.0 and 1.0 and that should be all drawn into the screen as in passing the clipping tests of the backend.

2020-07-06 16:57 UTC, CleanCut commented
> Edit: The old code should have worked, especially if that worked with specs.

The way that worked with specs can be seen [here](https://github.com/jlowry/amethyst/commit/f9f1ab209e1cfc6838802a6f1180fd1fd5238096#diff-09f645b3215c88ce31919f76f55dac90L83-L90) by using `Camera:standard_2d` (which has `0.0` centered on the screen) and a transform that translated the camera position so that `0.0` was in the bottom left. #1 was my attempt at directly replicating that approach. To make it work I had to negate the translation's x & y values (which maybe makes sense if the old `transform.set_translation_xyz()` method and legion_transform translation practices are inverses of each other?), and then discover and fix those z ranges for both the camera and the sprites.  But this worked with specs...so this is a pretty different behavior than before.

2020-07-06 17:15 UTC, CleanCut commented
/cc @athilenius as well, as the expert on legion_transform perhaps you have some insight here.

2020-07-06 17:52 UTC, AThilenius commented
This is all pretty old stuff for me too, got sidetracked with a new job 😋 Also not sure I understand the issue.

Legion transform works almost identical to Unity's new DOTs transforms, in case you need a reference. It's pretty simple in concept, you add any of [Translation, Rotation, Scale/NonUniformScale] as well as an optional [Parent] component if you want to parent the entity. These are used to compute and update a [LocalToWorld] component (which is a 4x4 matrix), as well as a [LocalToParent] component iff the entity was parented. If you were to use that on a camera though, you would need to invert the final matrix because the concept of a 'moving camera' in 3D graphics is an illusion (really the entire world moves as the inverse of the camera's transform). No idea if any of this helps lol.

2020-07-06 22:49 UTC, CleanCut commented
> If you were to use that on a camera though, you would need to invert the final matrix because the concept of a 'moving camera' in 3D graphics is an illusion (really the entire world moves as the inverse of the camera's transform). No idea if any of this helps lol.

I really appreciate your taking the time to comment, @AThilenius! I know how busy life can get. 😄 

Okay, I think that explains why the add-a-transform-to-the-camera needs negative numbers _now_, though it doesn't explain why it didn't use to.  Not super concerned about tracking down the old camera+transform behavior, though.

Now we just need to figure out what the heck is up with this orthogonal camera/projection behavior.

2020-07-07 08:17 UTC, valkum commented
Just to have it written down somewhere else than discord. I have not checked it but at a first glance it seems the camera gather in legion_v2 is wrong.
See the diff to master for this line https://github.com/amethyst/amethyst/blob/0d3d4730504f205b6edbbccdeade94ae903f0795/amethyst_rendy/src/submodules/gather.rs#L87

2020-07-07 17:45 UTC, CleanCut commented
@valkum I have taken a look at the diff, but I'm not seeing what you're seeing.  Can you explain what / how things look wrong?  Obviously the transform line is different...but we've switched from specs to legion in this branch, and that included a rewrite of the transform system, and I'm not sure what is semantically different here.

2020-07-07 18:08 UTC, valkum commented
The change is 
```diff
- let view = transform.global_view_matrix(); 
+ let view = &**transform;
```
https://docs-src.amethyst.rs/stable/amethyst_core/transform/components/struct.Transform.html#method.global_view_matrix calculates the inverse to create the view matrix.
My understanding is, that LocalToWorld is the translation including the Parent Translations of an entity, right?
So a view_matrix() implementation on LocalToWorld would be equal to global_view_matrix() on the old Transform component.

The legion code is missing that step it seems.
The camera.rs test code still uses a view_matrix() function on LocalToWorld but it seems that this is not implemented and a relic from specs.
I am not sure how Unity does this, as I could not find any quick information about Unity ECS Cameras.

So the way forward should be either upstream that to legion_transform (@jojolepro s version is currently used in legion_v2) or add an impementation somewhere in Amethyst (not sure if this works, maybe via extension traits?)

2020-07-07 18:44 UTC, valkum requested changes
Fix view_matrix computation in amethyst or upstream instead of adding a walkaround here.

Edit: Just closed this open Review. nvm the double posting.

2020-07-07 18:44 UTC, valkum commented on examples/pong_tutorial_02/pong.rs
> +    let camera = Camera::from(Projection::orthographic(
In current Amethyst, for both cameras, (0,0) should be in the center of the sceen, that is why the `standard_2d` halfs the width and height.

If for some reason it works if you create the matrix by hand with (0,0) in some corner, i suppose the translation is not correctly applied to the camera in the legion branch.

2020-07-08 00:31 UTC, CleanCut commented
> My understanding is, that LocalToWorld is the translation including the Parent Translations of an entity, right?

No idea. It's not documented and linear algebra is not one of my areas of expertise.

> So a view_matrix() implementation on LocalToWorld would be equal to global_view_matrix() on the old Transform component.

Okay, so if I understand you correctly, you are saying we should add a `view_matrix()` implementation to `legion_transform::LocalToWorld()` that does the same thing as what `global_view_matrix()` did, and then once that's done call `view_matrix()` here like this:

```diff
- let view = &**transform;
+ let view = transform.view_matrix()
```

I tried this locally first:

```diff
diff --git a/amethyst_rendy/src/submodules/gather.rs b/amethyst_rendy/src/submodules/gather.rs
index f0d3ecfe..527caa85 100644
--- a/amethyst_rendy/src/submodules/gather.rs
+++ b/amethyst_rendy/src/submodules/gather.rs
@@ -6,7 +6,7 @@ use crate::{
 };
 use amethyst_core::{
     ecs::prelude::*,
-    math::{convert, Matrix4, Vector3},
+    math::{self as na, convert, Matrix4, Vector3},
     transform::LocalToWorld,
 };
 use glsl_layout::*;
@@ -83,12 +83,31 @@ impl CameraGatherer {
 
         let camera_position = convert::<_, Vector3<f32>>(transform.column(3).xyz()).into_pod();
 
+        fn global_view_matrix(mut res: Matrix4<f32>) -> Matrix4<f32> {
+            // Perform an in-place inversion of the 3x3 matrix
+            {
+                let mut slice3x3 = res.fixed_slice_mut::<na::U3, na::U3>(0, 0);
+                assert!(slice3x3.try_inverse_mut());
+            }
+
+            let mut translation = -res.column(3).xyz();
+            translation = res.fixed_slice::<na::U3, na::U3>(0, 0) * translation;
+
+            let mut res_trans = res.column_mut(3);
+            res_trans.x = translation.x;
+            res_trans.y = translation.y;
+            res_trans.z = translation.z;
+
+            res
+        }
+
         let proj = camera.as_matrix();
-        let view = &**transform;
+        let view = global_view_matrix(transform.0);
 
         let proj_view: [[f32; 4]; 4] = ((*proj) * view).into();
         let proj: [[f32; 4]; 4] = (*proj).into();
-        let view: [[f32; 4]; 4] = (*view).into();
+        let view: [[f32; 4]; 4] = view.into();
+        dbg!(view);
 
         let projview = pod::ViewArgs {
             proj: proj.into(),
```

And absolutely nothing changed.  Probably because view ends up as this matrix before AND after the change (well, technically it has `-0.0` on some of the `0.0` entries after the change, but I don't think the sign on `0` changes anything):
```
view = [
    [
        1.0,
        0.0,
        0.0,
        0.0,
    ],
    [
        0.0,
        1.0,
        0.0,
        0.0,
    ],
    [
        0.0,
        0.0,
        1.0,
        0.0,
    ],
    [
        0.0,
        0.0,
        0.0,
        1.0,
    ],
]
```

That looks like the identity matrix to me, so if there is a problem around here, maybe it has to do with [how we try to obtain the transform in the first place](https://github.com/amethyst/amethyst/blob/0d3d4730504f205b6edbbccdeade94ae903f0795/amethyst_rendy/src/submodules/gather.rs#L79-L82).

I'll try to take a look at that later tonight if I get some time.

2020-07-08 05:53 UTC, CleanCut commented
Hmm. `transform` was always the identity because I had removed the translation component from the pong example.  Don’t have time to dig any further tonight.

2020-07-08 14:37 UTC, valkum commented
Let me invest a couple of minutes (hopefully not hours)

2020-07-08 15:11 UTC, valkum commented
I put up a PR to your branch. That works for me with the vulkan backend. I see the paddles.

2020-07-08 17:55 UTC, CleanCut commented
Okay, so if I'm understanding correctly, with the correct view matrix logic (inverting the camera's translation matrix), we're able at least to have the camera translation work as it did before, and apparently rendering sprites at 0.0 also works correctly.  I still don't understand why manually setting up the orthographic projection doesn't work correctly, but that's probably just me not understanding the math and doing something wrong, so let's push forward.

Next question: Is this the only place that we'll ever want to get the view matrix for a LocalToWorld transform?  My guess is "no" and that we should submit a PR in legion_transform to add a version of this `global_view_matrix` function as a method to legion_transform, I'm guessing as `LocalToWorld::view_matrix()` would probably be the sensible name/place.

2020-07-12 12:20 UTC, merged

2020-07-16 22:48 UTC, CleanCut commented
I still intend to move that `global_view_matrix` function up into a method of  `legion_transform`'s `LocalToWorld::view_matrix()` -- I got distracted by a series of events and discussions (picked the wrong `legion_transform` fork, which spurred a conversation about ownership of `legion_transform`, ... etc.)